name: CI 1
on: [push]
jobs:
  standard-checks:
    name: Linting and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Clean install dependencies
        run: rm -rf node_modules && yarn

      - name: Run ESlint
        run: yarn lint

      - name: Build & Bundle
        run: yarn build
